// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfapwyajqwqpzmxwexdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmYXB3eWFqcXdxcHpteHdleGRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MzA1MTgsImV4cCI6MjA2MzEwNjUxOH0.Lw-G5zXjzP8T1rvYkmUeXywZSfYJF93BLBJAhoq0x8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);